### ISSUE TITLE
Create volume should use clusterId not clusterID

### ISSUE THREAD

**Issue by aorourkehp** [hp-storage/python-lefthandclient#3]
The JSON posted from createVolume is not in the proper format the LeftHand API expects it. It should be clusterId instead of clusterID. When using just clusterID, the following error is thrown: "*Cluster ID or name MUST be specified when creating a volume and more than one cluster is defined in the managment group.*"

In createVolume the following is posted:
`info = {'name': name, 'clusterID': cluster_id, 'size': size}`

The LeftHand API expects:
`info = {'name': name, 'clusterId': cluster_id, 'size': size}`

clusterName is an optional parameter, that when provided to the LeftHand API, will look for the cluster via its name rather than ID. In the LeftHand driver, clusterName is provided which allows for the proper finding of the cluster. But if you call createVolume directly while providing only the mandatory parameters and not the optional ones, it fails.

**Comment by hp-storage** [comment]
Released in version 1.0.6
